/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatProjectsRouteImport } from './routes/_chat.projects'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatSourceControlProjectIdRouteImport } from './routes/_chat.source-control.$projectId'
import { Route as ChatShellsProjectIdRouteImport } from './routes/_chat.shells.$projectId'
import { Route as ChatFilesProjectIdRouteImport } from './routes/_chat.files.$projectId'
import { Route as ChatShellsProjectIdIndexRouteImport } from './routes/_chat.shells.$projectId.index'
import { Route as ChatShellsProjectIdShellIdRouteImport } from './routes/_chat.shells.$projectId.$shellId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatProjectsRoute = ChatProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSourceControlProjectIdRoute =
  ChatSourceControlProjectIdRouteImport.update({
    id: '/source-control/$projectId',
    path: '/source-control/$projectId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatShellsProjectIdRoute = ChatShellsProjectIdRouteImport.update({
  id: '/shells/$projectId',
  path: '/shells/$projectId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatFilesProjectIdRoute = ChatFilesProjectIdRouteImport.update({
  id: '/files/$projectId',
  path: '/files/$projectId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatShellsProjectIdIndexRoute =
  ChatShellsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ChatShellsProjectIdRoute,
  } as any)
const ChatShellsProjectIdShellIdRoute =
  ChatShellsProjectIdShellIdRouteImport.update({
    id: '/$shellId',
    path: '/$shellId',
    getParentRoute: () => ChatShellsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/projects': typeof ChatProjectsRoute
  '/files/$projectId': typeof ChatFilesProjectIdRoute
  '/shells/$projectId': typeof ChatShellsProjectIdRouteWithChildren
  '/source-control/$projectId': typeof ChatSourceControlProjectIdRoute
  '/shells/$projectId/$shellId': typeof ChatShellsProjectIdShellIdRoute
  '/shells/$projectId/': typeof ChatShellsProjectIdIndexRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/projects': typeof ChatProjectsRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/': typeof ChatIndexRoute
  '/files/$projectId': typeof ChatFilesProjectIdRoute
  '/source-control/$projectId': typeof ChatSourceControlProjectIdRoute
  '/shells/$projectId/$shellId': typeof ChatShellsProjectIdShellIdRoute
  '/shells/$projectId': typeof ChatShellsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/projects': typeof ChatProjectsRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/files/$projectId': typeof ChatFilesProjectIdRoute
  '/_chat/shells/$projectId': typeof ChatShellsProjectIdRouteWithChildren
  '/_chat/source-control/$projectId': typeof ChatSourceControlProjectIdRoute
  '/_chat/shells/$projectId/$shellId': typeof ChatShellsProjectIdShellIdRoute
  '/_chat/shells/$projectId/': typeof ChatShellsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/projects'
    | '/settings'
    | '/files/$projectId'
    | '/shells/$projectId'
    | '/source-control/$projectId'
    | '/shells/$projectId/$shellId'
    | '/shells/$projectId/'
    | '/settings'
    | '/$threadId'
    | '/settings/archived'
    | '/settings/general'
    | '/files/$projectId'
    | '/shells/$projectId'
    | '/source-control/$projectId'
    | '/shells/$projectId/$shellId'
    | '/shells/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/$threadId'
    | '/projects'
    | '/settings/archived'
    | '/settings/general'
    | '/'
    | '/files/$projectId'
    | '/source-control/$projectId'
    | '/shells/$projectId/$shellId'
    | '/shells/$projectId'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/_chat/$threadId'
    | '/_chat/projects'
    | '/settings/archived'
    | '/settings/general'
    | '/_chat/'
    | '/_chat/files/$projectId'
    | '/_chat/shells/$projectId'
    | '/_chat/source-control/$projectId'
    | '/_chat/shells/$projectId/$shellId'
    | '/_chat/shells/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/projects': {
      id: '/_chat/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ChatProjectsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/source-control/$projectId': {
      id: '/_chat/source-control/$projectId'
      path: '/source-control/$projectId'
      fullPath: '/source-control/$projectId'
      preLoaderRoute: typeof ChatSourceControlProjectIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/shells/$projectId': {
      id: '/_chat/shells/$projectId'
      path: '/shells/$projectId'
      fullPath: '/shells/$projectId'
      preLoaderRoute: typeof ChatShellsProjectIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/files/$projectId': {
      id: '/_chat/files/$projectId'
      path: '/files/$projectId'
      fullPath: '/files/$projectId'
      preLoaderRoute: typeof ChatFilesProjectIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/shells/$projectId/': {
      id: '/_chat/shells/$projectId/'
      path: '/'
      fullPath: '/shells/$projectId/'
      preLoaderRoute: typeof ChatShellsProjectIdIndexRouteImport
      parentRoute: typeof ChatShellsProjectIdRoute
    }
    '/_chat/shells/$projectId/$shellId': {
      id: '/_chat/shells/$projectId/$shellId'
      path: '/$shellId'
      fullPath: '/shells/$projectId/$shellId'
      preLoaderRoute: typeof ChatShellsProjectIdShellIdRouteImport
      parentRoute: typeof ChatShellsProjectIdRoute
    }
  }
}

interface ChatShellsProjectIdRouteChildren {
  ChatShellsProjectIdShellIdRoute: typeof ChatShellsProjectIdShellIdRoute
  ChatShellsProjectIdIndexRoute: typeof ChatShellsProjectIdIndexRoute
}

const ChatShellsProjectIdRouteChildren: ChatShellsProjectIdRouteChildren = {
  ChatShellsProjectIdShellIdRoute: ChatShellsProjectIdShellIdRoute,
  ChatShellsProjectIdIndexRoute: ChatShellsProjectIdIndexRoute,
}

const ChatShellsProjectIdRouteWithChildren =
  ChatShellsProjectIdRoute._addFileChildren(ChatShellsProjectIdRouteChildren)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatProjectsRoute: typeof ChatProjectsRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatFilesProjectIdRoute: typeof ChatFilesProjectIdRoute
  ChatShellsProjectIdRoute: typeof ChatShellsProjectIdRouteWithChildren
  ChatSourceControlProjectIdRoute: typeof ChatSourceControlProjectIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatProjectsRoute: ChatProjectsRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatFilesProjectIdRoute: ChatFilesProjectIdRoute,
  ChatShellsProjectIdRoute: ChatShellsProjectIdRouteWithChildren,
  ChatSourceControlProjectIdRoute: ChatSourceControlProjectIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
