/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatProjectsRouteImport } from './routes/_chat.projects'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatShellsProjectIdRouteImport } from './routes/_chat.shells.$projectId'
import { Route as ChatShellsProjectIdIndexRouteImport } from './routes/_chat.shells.$projectId.index'
import { Route as ChatShellsProjectIdShellIdRouteImport } from './routes/_chat.shells.$projectId.$shellId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatProjectsRoute = ChatProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatShellsProjectIdRoute = ChatShellsProjectIdRouteImport.update({
  id: '/shells/$projectId',
  path: '/shells/$projectId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatShellsProjectIdIndexRoute =
  ChatShellsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ChatShellsProjectIdRoute,
  } as any)
const ChatShellsProjectIdShellIdRoute =
  ChatShellsProjectIdShellIdRouteImport.update({
    id: '/$shellId',
    path: '/$shellId',
    getParentRoute: () => ChatShellsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/projects': typeof ChatProjectsRoute
  '/settings': typeof ChatSettingsRoute
  '/shells/$projectId': typeof ChatShellsProjectIdRouteWithChildren
  '/shells/$projectId/$shellId': typeof ChatShellsProjectIdShellIdRoute
  '/shells/$projectId/': typeof ChatShellsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/projects': typeof ChatProjectsRoute
  '/settings': typeof ChatSettingsRoute
  '/': typeof ChatIndexRoute
  '/shells/$projectId/$shellId': typeof ChatShellsProjectIdShellIdRoute
  '/shells/$projectId': typeof ChatShellsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/projects': typeof ChatProjectsRoute
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/shells/$projectId': typeof ChatShellsProjectIdRouteWithChildren
  '/_chat/shells/$projectId/$shellId': typeof ChatShellsProjectIdShellIdRoute
  '/_chat/shells/$projectId/': typeof ChatShellsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/projects'
    | '/settings'
    | '/shells/$projectId'
    | '/shells/$projectId/$shellId'
    | '/shells/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$threadId'
    | '/projects'
    | '/settings'
    | '/'
    | '/shells/$projectId/$shellId'
    | '/shells/$projectId'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/projects'
    | '/_chat/settings'
    | '/_chat/'
    | '/_chat/shells/$projectId'
    | '/_chat/shells/$projectId/$shellId'
    | '/_chat/shells/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/projects': {
      id: '/_chat/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ChatProjectsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/shells/$projectId': {
      id: '/_chat/shells/$projectId'
      path: '/shells/$projectId'
      fullPath: '/shells/$projectId'
      preLoaderRoute: typeof ChatShellsProjectIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/shells/$projectId/': {
      id: '/_chat/shells/$projectId/'
      path: '/'
      fullPath: '/shells/$projectId/'
      preLoaderRoute: typeof ChatShellsProjectIdIndexRouteImport
      parentRoute: typeof ChatShellsProjectIdRoute
    }
    '/_chat/shells/$projectId/$shellId': {
      id: '/_chat/shells/$projectId/$shellId'
      path: '/$shellId'
      fullPath: '/shells/$projectId/$shellId'
      preLoaderRoute: typeof ChatShellsProjectIdShellIdRouteImport
      parentRoute: typeof ChatShellsProjectIdRoute
    }
  }
}

interface ChatShellsProjectIdRouteChildren {
  ChatShellsProjectIdShellIdRoute: typeof ChatShellsProjectIdShellIdRoute
  ChatShellsProjectIdIndexRoute: typeof ChatShellsProjectIdIndexRoute
}

const ChatShellsProjectIdRouteChildren: ChatShellsProjectIdRouteChildren = {
  ChatShellsProjectIdShellIdRoute: ChatShellsProjectIdShellIdRoute,
  ChatShellsProjectIdIndexRoute: ChatShellsProjectIdIndexRoute,
}

const ChatShellsProjectIdRouteWithChildren =
  ChatShellsProjectIdRoute._addFileChildren(ChatShellsProjectIdRouteChildren)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatProjectsRoute: typeof ChatProjectsRoute
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatShellsProjectIdRoute: typeof ChatShellsProjectIdRouteWithChildren
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatProjectsRoute: ChatProjectsRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatShellsProjectIdRoute: ChatShellsProjectIdRouteWithChildren,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
